[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-sqlalchemy>=3.1.1",
    "flask>=3.1.0",
    "werkzeug>=3.1.3",
    "flask-migrate>=4.1.0",
    "flask-babel>=4.0.0",
]
